### PR TITLE
Speeding up actions

### PR DESCRIPTION
**Pull request by bandophahita**

### CODE REVIEW

**Comment by perrygoy** [comment]
I think you've gotten a PR merged in to Selenium to fix these failing lint steps, right? Should we wait for that to be released?

**Comment by bandophahita** [comment]
> I think you've gotten a PR merged in to Selenium to fix these failing lint steps, right? Should we wait for that to be released?

I wasn't sure how long it would be till that fix is out and I wanted to be able to work on this and other PRs in the mean time.

**Comment by bandophahita** [comment]
Rebased trunk into this branch with the mypy work-around.  This PR passes now.

**Review by perrygoy — APPROVED** [review]
🎉 🎉 🎉 💨

**Pull request merged**
